<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net35</TargetFramework>
        <AssemblyName>SceneFX</AssemblyName>
        <RootNamespace>SceneFX</RootNamespace>
        <LangVersion>7.3</LangVersion>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <Product>SceneFX</Product>
        <Version>2.1.0</Version>
        <ManagedDLLPath Condition="'$(ManagedDLLPath)' == ''">$(MSBuildProgramFiles32)/Steam/steamapps/common/Cities_Skylines/Cities_Data/Managed</ManagedDLLPath>
        <FrameworkPathOverride>$(ManagedDLLPath)</FrameworkPathOverride>
        <AssemblySearchPaths>$(AssemblySearchPaths);$(ManagedDLLPath)</AssemblySearchPaths>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="tests\**\*.cs" />
        <EmbeddedResource Include="BuiltIns\Optimized.xml" />
        <EmbeddedResource Include="BuiltIns\Optimized.suite.xml" />
        <Reference Include="Assembly-CSharp" />
        <Reference Include="Assembly-CSharp-firstpass" />
        <Reference Include="ColossalManaged" />
        <Reference Include="ICities" />
        <Reference Include="UnityEngine" />
        <Reference Include="System.Xml" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

    <Target Name="DeployToModDirectory" AfterTargets="Build" Condition="'$(DeployMod)' == 'true'">
        <PropertyGroup>
            <DeployDir>$(LOCALAPPDATA)/Colossal Order/Cities_Skylines/Addons/Mods/SceneFX/</DeployDir>
        </PropertyGroup>
        <MakeDir Directories="$(DeployDir)" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DeployDir)" />
        <ItemGroup>
            <LocaleFiles Include="Locale\*.xml" />
        </ItemGroup>
        <Copy SourceFiles="@(LocaleFiles)" DestinationFolder="$(DeployDir)Locale/" SkipUnchangedFiles="true" />
        <Message Importance="high" Text="Deployed to $(DeployDir)" />
    </Target>

</Project>
