using System;
using System.Collections.Generic;
using System.Globalization;
using ColossalFramework.Globalization;
namespace SceneFX.UI
{
    internal static class UiText
    {
        private static readonly Dictionary<string, string> Spanish = new Dictionary<string, string> {
            { "Game", "Juego" },
            { "Manual", "Manual" },
            { "Off", "Desactivado" },
            { "On", "Activado" },
            { "Undo", "Deshacer" },
            { "Camera", "Cámara" },
            { "Weather", "Clima" },
            { "Time", "Tiempo" },
            { "Presets", "Presets" },
            { "Light", "Luz" },
            { "Advanced", "Avanzado" },
            { "Classic", "Clásico" },
            { "Fog", "Niebla" },
            { "Volume", "Volumen" },
            { "Depth", "Profundidad" },
            { "Name", "Nombre" },
            { "Colour correction LUT", "LUT de color" },
            { "LUT correction", "Corrección LUT" },
            { "Camera tonemapping", "Mapeo tonal de cámara" },
            { "Game bloom", "Bloom del juego" },
            { "Lock rain / snow intensity", "Fijar intensidad de lluvia/nieve" },
            { "Rain / snow intensity", "Intensidad de lluvia/nieve" },
            { "Lock weather fog", "Fijar niebla meteorológica" },
            { "Weather fog", "Niebla meteorológica" },
            { "Lock clouds", "Fijar nubes" },
            { "Clouds", "Nubes" },
            { "Lock northern lights", "Fijar auroras" },
            { "Northern lights", "Auroras" },
            { "Lock rainbow", "Fijar arcoíris" },
            { "Rainbow", "Arcoíris" },
            { "Lock ground wetness", "Fijar humedad del suelo" },
            { "Ground wetness", "Humedad del suelo" },
            { "Lock temperature", "Fijar temperatura" },
            { "Temperature (C)", "Temperatura (°C)" },
            { "Lock wind direction", "Fijar dirección del viento" },
            { "Wind direction", "Dirección del viento" },
            { "Dynamic weather", "Clima dinámico" },
            { "Snow instead of rain", "Nieve en lugar de lluvia" },
            { "Snow on roads", "Nieve en carreteras" },
            { "Rain motion blur", "Desenfoque de lluvia" },
            { "Hour (0–24)", "Hora (0–24)" },
            { "Lock hour", "Fijar hora" },
            { "Latitude", "Latitud" },
            { "Longitude", "Longitud" },
            { "Game speed", "Velocidad de simulación" },
            { "Control visual day/night speed", "Controlar velocidad visual día/noche" },
            { "Day speed (1 = game)", "Velocidad diurna (1 = juego)" },
            { "Separate night speed", "Velocidad nocturna independiente" },
            { "Night speed", "Velocidad nocturna" },
            { "Continue visual cycle while paused", "Continuar ciclo visual en pausa" },
            { "Pause / resume simulation", "Pausar/reanudar simulación" },
            { "Saved preset", "Preset guardado" },
            { "Apply selected preset", "Aplicar preset seleccionado" },
            { "Include world in this preset", "Incluir mundo en este preset" },
            { "Save preset", "Guardar preset" },
            { "Refresh presets", "Actualizar lista de presets" },
            { "Migrate legacy preset to suite", "Migrar preset antiguo a suite" },
            { "Saved suite", "Suite guardada" },
            { "Apply selected suite", "Aplicar suite seleccionada" },
            { "Save all four FX as suite", "Guardar los cuatro FX como suite" },
            { "Apply settings when a city loads", "Aplicar ajustes al cargar ciudad" },
            { "Sun power (0 = map)", "Intensidad solar (0 = mapa)" },
            { "Moon power (0 = map)", "Intensidad lunar (0 = mapa)" },
            { "Sun colour gain", "Ganancia de color solar" },
            { "Moon colour gain", "Ganancia de color lunar" },
            { "Ambient gain", "Ganancia ambiental" },
            { "Rayleigh (0 = map)", "Rayleigh (0 = mapa)" },
            { "Mie (0 = map)", "Mie (0 = mapa)" },
            { "Sky exposure (0 = map)", "Exposición del cielo (0 = mapa)" },
            { "Sky tonemapping", "Mapeo tonal del cielo" },
            { "Overall warmth", "Calidez general" },
            { "Overall tint", "Tinte general" },
            { "Sun temperature", "Temperatura solar" },
            { "Sun tint", "Tinte solar" },
            { "Moon temperature", "Temperatura lunar" },
            { "Moon tint", "Tinte lunar" },
            { "Sky temperature", "Temperatura ambiental" },
            { "Sky tint", "Tinte ambiental" },
            { "Twilight tint", "Tinte crepuscular" },
            { "Camera tone", "Tono de cámara" },
            { "Brightness", "Brillo" },
            { "Contrast", "Contraste" },
            { "Soft shadows", "Sombras suaves" },
            { "Adaptive shadow bias", "Sesgo adaptativo de sombras" },
            { "Force low shadow bias", "Forzar sesgo bajo de sombras" },
            { "Shadow bias scale", "Escala del sesgo de sombras" },
            { "Adaptive exposure", "Exposición adaptativa" },
            { "Adaptive exposure gain", "Ganancia de exposición adaptativa" },
            { "Refresh list", "Actualizar lista" },
            { "Import installed .light presets", "Importar presets .light instalados" },
            { "Use imported Scene lighting model", "Usar modelo de iluminación Scene importado" },
            { "Dynamic fog", "Niebla dinámica" },
            { "Fog start (m)", "Inicio de niebla (m)" },
            { "Horizon (m)", "Horizonte (m)" },
            { "Fog ceiling (m)", "Techo de niebla (m)" },
            { "Density", "Densidad" },
            { "Colour decay", "Atenuación de color" },
            { "Noise", "Ruido" },
            { "Wind drift", "Deriva del viento" },
            { "Dynamic edge fog", "Niebla dinámica en bordes" },
            { "Classic edge fog", "Niebla clásica en bordes" },
            { "Classic fog", "Niebla clásica" },
            { "Disable classic fog at night", "Desactivar niebla clásica de noche" },
            { "Volumetric fog", "Niebla volumétrica" },
            { "Scatter intensity", "Intensidad de dispersión" },
            { "Scatter exponent", "Exponente de dispersión" },
            { "Scatter red", "Dispersión: rojo" },
            { "Scatter green", "Dispersión: verde" },
            { "Scatter blue", "Dispersión: azul" },
            { "Automatic volume colour", "Color volumétrico automático" },
            { "Volume red", "Volumen: rojo" },
            { "Volume green", "Volumen: verde" },
            { "Volume blue", "Volumen: azul" },
            { "Volume start (m)", "Inicio de volumen (m)" },
            { "Classic volume fog", "Volumen de niebla clásica" },
            { "Static Height", "Altura estática" },
            { "Static Start", "Inicio estático" },
            { "Static Distance", "Distancia estática" },
            { "Static Edge Distance", "Distancia de borde estático" },
            { "Volume Height", "Altura volumétrica" },
            { "Volume Density", "Densidad volumétrica" },
            { "Volume Distance", "Distancia volumétrica" },
            { "Volume Edge Distance", "Distancia de borde volumétrico" },
            { "Scatter colour", "Color de dispersión" },
            { "Automatic", "Automático" },
            { "Sun matched", "Seguir color solar" },
            { "Custom RGB", "RGB personalizado" },
            { "Procedural classic stock LUTs", "LUT clásicas procedurales" },
            { "Classic daylight approximation", "Aproximación de luz clásica" },
            { "Classic sun strength", "Intensidad solar clásica" },
            { "Classic sun coordinates", "Coordenadas solares clásicas" },
            { "Classic fog effect", "Efecto de niebla clásica" },
            { "Classic atmospheric tint", "Tinte atmosférico clásico" },
            { "Allow classic fog with day/night cycle", "Permitir niebla clásica con ciclo día/noche" },
            { "Enable all classic features", "Activar todas las funciones clásicas" },
            { "Restore value at panel opening", "Restaurar valor al abrir el panel" },
            { "Reset this setting", "Restablecer este ajuste" },
            { "Controlled by the selected mode; switch to Manual to edit", "Controlado por el modo seleccionado; elige Manual para editar" },
            { "Release this mod's changes and keep that mode across cities.", "Liberar los cambios de este mod y conservar este modo entre ciudades." },
            { "Apply this mod's part of Render It Plus / Default.", "Aplicar la parte de Render It Plus / Default que corresponde a este mod." },
        };
        internal static string Get(string text)
        {
            if (text == null) return string.Empty;
            string language = LocaleManager.exists ? LocaleManager.instance.language : CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
            if (language == null || !language.StartsWith("es", StringComparison.OrdinalIgnoreCase)) return text;
            string translated;
            if (Spanish.TryGetValue(text, out translated)) return translated;
            if (text.EndsWith(" mode", StringComparison.Ordinal)) return Get(text.Substring(0, text.Length - 5)) + ": modo";
            return text;
        }
        internal static string[] Items(string[] values) { return Array.ConvertAll(values, Get); }
    }
}
