using System;
using System.IO;
using System.Reflection;
using System.Xml.Serialization;
using UnityEngine;
using SceneFX.Core;
using LumenFX.Runtime;
using AC = AtmosphereFX.Config.ModConfig;
using AO = AtmosphereFX.Config.ConfigStore;
using CO = ClassicLightFX.Options.ModOptions;
partial class Program {
 static int pass,fail;
 static string ConfigDir=>ColossalFramework.IO.DataLocation.localApplicationData;
 static void Check(string id,bool ok,string detail) { Console.WriteLine((ok?"PASS ":"FAIL ")+id+" | "+detail);if(ok)pass++;else fail++; }
 static bool Equal(float a,float b)=>Math.Abs(a-b)<.00000001f;
 static void Call(object o,string name) {o.GetType().GetMethod(name,BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public).Invoke(o,null);}
 static string Xml<T>(T o){var w=new StringWriter();new XmlSerializer(typeof(T)).Serialize(w,o);return w.ToString();}
 static void Read<T>(string xml){new XmlSerializer(typeof(T)).Deserialize(new StringReader(xml));}
 static void FreshWorld() {
  ClassicLightFX.Core.ClassicLook.Detach();
  AppDomain.CurrentDomain.SetData("FX.ClassicRequests.v1", string.Empty);
  AppDomain.CurrentDomain.SetData("FX.PropertyLedger.v1", null);
  UnityEngine.Object.Registry.Clear();
  DayNightProperties.instance=new DayNightProperties();new FogProperties();new FogEffect();new DayNightFogEffect();new RenderProperties();
  new GameObject("Main Camera");new ColossalFramework.ToneMapping();
  AtmosphereFX.Runtime.SettingsApplier.ClearCache();AtmosphereFX.Runtime.VanillaSnapshot.ResetCapture();
  LumenFX.Core.VanillaSnapshot.ResetCapture();LumenFX.Core.LightingMixer.ClearCache();
  StyleEngine.ClearCache();WorldController.ClearCache();TimeController.ClearCache();WorldController.Restore();TimeController.Restore();
  ColorCorrectionManager.instance = new ColorCorrectionManager();
  typeof(SceneRuntime).GetField("_current",BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,new StyleData());
  SceneRuntime.Active=false;
  CO.Instance.VanillaMode=false;
  AC.RestoreVanilla();AC.VanillaMode=false;SceneRuntime.VanillaMode=false;
  TunerRuntime.CurrentState.ResetToNeutral();TunerRuntime.CurrentState.VanillaMode=false;
  typeof(LumenFX.LumenFXMod).GetField("_patched",BindingFlags.Static|BindingFlags.NonPublic).SetValue(null,true);
  SimulationManager.instance.m_enableDayNight=true;SimulationManager.instance.m_isNightTime=false;
  Time.realtimeSinceStartup+=10;
 }
 static void Main() {
  Directory.CreateDirectory(ConfigDir);
  Directory.SetCurrentDirectory(ConfigDir); // legacy fallback paths are isolated too
  Console.WriteLine("Regression of current FX source; .NET 8 doubles, NOT the Unity/Mono game runtime.");
  FreshWorld();
  var state=TunerRuntime.CurrentState;
  state.Brightness=1.25f;state.Gamma=2.8f;state.SkyRayleigh=1.116f;state.SkyMie=1.858f;state.SunPower=2.35f;state.MoonPower=.8f;
  LumenFX.IO.StateStore.SaveImmediate();
  string saved=File.ReadAllText(Path.Combine(ConfigDir,"LumenFX2.xml"));
  state.ResetToNeutral();LumenFX.IO.StateStore.Load();
  Check("L01 base Lumen settings round-trip",Equal(state.Brightness,1.25f)&&Equal(state.Gamma,2.8f),"brightness="+state.Brightness+" gamma="+state.Gamma);
  Check("L02 all four absolute lighting settings survive restart",Equal(state.SkyRayleigh,1.116f)&&Equal(state.SkyMie,1.858f)&&Equal(state.SunPower,2.35f)&&Equal(state.MoonPower,.8f),"after save/reset/load: Rayleigh="+state.SkyRayleigh+" Mie="+state.SkyMie+" SunPower="+state.SunPower+" MoonPower="+state.MoonPower);
  AC.Density=.000123f;AC.WindSpeed=.0001f;AC.EdgeFogDynamic=false;AC.EdgeFogCubemap=true;AO.SaveImmediate();AC.RestoreVanilla();AO.Load();
  Check("A01 normal global Atmosphere settings round-trip",Equal(AC.Density,.000123f)&&Equal(AC.WindSpeed,.0001f)&&!AC.EdgeFogDynamic&&AC.EdgeFogCubemap,"density="+AC.Density+" wind="+AC.WindSpeed);
  string suite=AtmosphereFX.AtmosphereFXMod.ExportSuiteSection();AtmosphereFX.AtmosphereFXMod.ApplySuiteSection(suite);
  Check("A02 suite export preserves usable wind precision",Equal(AC.WindSpeed,.0001f),"0.0001 -> "+AC.WindSpeed);
  CO.Instance.ClassicFogWithCycle=true;CO.Instance.SunColor=false;CO.SaveImmediate();CO.Instance.ClassicFogWithCycle=false;CO.Instance.SunColor=true;CO.Load();
  Check("C01 Classic options round-trip",CO.Instance.ClassicFogWithCycle&&!CO.Instance.SunColor,"ClassicFogWithCycle="+CO.Instance.ClassicFogWithCycle+" SunColor="+CO.Instance.SunColor);
  FreshWorld();
  var fog=UnityEngine.Object.FindObjectOfType<FogProperties>();float originalDensity=fog.m_FogDensity;
  AC.Density=.00006f;AtmosphereFX.Runtime.SettingsApplier.ApplyAll();AtmosphereFX.Config.QuickPresets.ApplyVanilla();
  Check("A03 Vanilla quick preset restores captured fog",Equal(fog.m_FogDensity,originalDensity),"expected="+originalDensity+" actual="+fog.m_FogDensity+" VanillaMode="+AC.VanillaMode);
  FreshWorld();
  AtmosphereFX.AtmosphereFXMod.ApplySuiteSection("<atmospherefx><density>NaN</density></atmospherefx>");
  Check("A04 reject non-finite fog config",!float.IsNaN(UnityEngine.Object.FindObjectOfType<FogProperties>().m_FogDensity),"engine fog density="+UnityEngine.Object.FindObjectOfType<FogProperties>().m_FogDensity);
  FreshWorld();
  LumenFX.LumenFXMod.ApplySuiteSection("<lumenfx><gamma>NaN</gamma></lumenfx>");
  Check("L03 reject non-finite gamma",!float.IsNaN(UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingGamma),"engine gamma="+UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingGamma);
  FreshWorld();
  CO.Instance.ApplyOnLoad=false;CO.Instance.ClassicFogMode=true;CO.Instance.ClassicFogTint=true;CO.Instance.ClassicFogWithCycle=false;
  ClassicLightFX.Core.ClassicLook.Attach();
  Call(UnityEngine.Object.FindObjectOfType<ClassicLightFX.Core.ClassicFogDriver>(),"Update");
  Check("C02 ApplyOnLoad=false keeps fog untouched",UnityEngine.Object.FindObjectOfType<DayNightFogEffect>().enabled&&!UnityEngine.Object.FindObjectOfType<FogEffect>().enabled,"dynamic="+UnityEngine.Object.FindObjectOfType<DayNightFogEffect>().enabled+" classic="+UnityEngine.Object.FindObjectOfType<FogEffect>().enabled);
  // Retain requirement-level truth table, not copied legacy implementation.
  ClassicLightFX.Core.ClassicLook.ApplyFromOptions();
  int mismatch=0;
  foreach(bool cycle in new[]{false,true})foreach(bool night in new[]{false,true})foreach(bool allow in new[]{false,true}) {
   CO.Instance.ClassicFogMode=true;CO.Instance.ClassicFogWithCycle=allow;
   SimulationManager.instance.m_enableDayNight=cycle;SimulationManager.instance.m_isNightTime=night;
   var driver=UnityEngine.Object.FindObjectOfType<ClassicLightFX.Core.ClassicFogDriver>();driver.Refresh();Call(driver,"Update");
   bool actual=UnityEngine.Object.FindObjectOfType<FogEffect>().enabled;
   bool expected=!night&&(!cycle||allow);
   if(actual!=expected){mismatch++;Console.WriteLine("  C03 case cycle="+cycle+" night="+night+" allow="+allow+" legacy="+expected+" FX="+actual);}
  }
  Check("C03 classic fog cycle behavior equals Daylight Classic",mismatch==0,"mismatches="+mismatch+"/8");
  FreshWorld();
  ClassicLightFX.Core.ClassicLook.Attach();state.SunPower=6f;state.LightingDirty=true;TunerRuntime.ApplyAll();
  ClassicLightFX.Core.ClassicLook.Apply(ClassicLightFX.Core.ClassicFeature.SunPower,true);
  Check("X01 Classic respects active Lumen sun power",Equal(DayNightProperties.instance.m_SunIntensity,6f),"Lumen requested 6; Classic changed actual to "+DayNightProperties.instance.m_SunIntensity);
  FreshWorld();
  SceneRuntime.Current.Rain=-1;SceneRuntime.Current.GameSpeed=1;SceneRuntime.Current.IncludeWorld=false;
  WorldController.SetChannel("rain",.8f);TimeController.ApplyGameSpeed(2f);WorldController.TimeLocked=true;SceneRuntime.WorldChanged();
  var host=new SceneFX.PanelEngine();Call(host,"OnDestroy");SceneRuntime.LoadPersisted();
  Check("S01 UI weather and speed reach automatic settings",Equal(SceneRuntime.Current.Rain,.8f)&&Equal(SceneRuntime.Current.GameSpeed,2),"saved rain="+SceneRuntime.Current.Rain+" saved gameSpeed="+SceneRuntime.Current.GameSpeed);
  Check("S02 hour lock is serializable",typeof(StyleData).GetField("TimeLocked")!=null||typeof(OptionsDocument).GetField("TimeLocked")!=null,"TimeLocked member persists in the settings schema");
  FreshWorld();
  SceneRuntime.Current.IncludeWorld=false;WorldController.SetChannel("rain",.7f);TimeController.ApplyGameSpeed(2.5f);
  var manual=SceneRuntime.Current.Clone();manual.IncludeWorld=true;StyleEngine.CaptureWorld(manual);
  var roundtrip=(StyleData)new XmlSerializer(typeof(StyleData)).Deserialize(new StringReader(Xml(manual)));
  Check("S03 explicit world capture preserves weather/speed",Equal(roundtrip.Rain,.7f)&&Equal(roundtrip.GameSpeed,2.5f),"rain="+roundtrip.Rain+" gameSpeed="+roundtrip.GameSpeed);
  FreshWorld();
  SceneRuntime.Current.IncludeWorld=false;Time.realtimeSinceStartup=100;SceneRuntime.Current.Brightness=.1f;SceneRuntime.ApplyCurrent();
  Time.realtimeSinceStartup=100.2f;SceneRuntime.Current.Brightness=.2f;SceneRuntime.ApplyCurrent();Time.realtimeSinceStartup=110;Call(new SceneFX.PanelEngine(),"Update");
  var stored=StyleStore.LoadState();
  Check("S04 last slider value flushes after throttle interval",Equal(stored.Brightness,.2f),"current=.2 file="+stored.Brightness+" after 10 seconds; clean unload not tested here");
  FreshWorld();
  StyleEngine.CaptureBaseline();state.Brightness=2;TunerRuntime.ApplyAll();float lumenBoost=UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingBoostFactor;
  SceneRuntime.RestoreGame();
  Check("X02 Scene restore respects active Lumen tone",Equal(UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingBoostFactor,lumenBoost),"Lumen boost="+lumenBoost+" after Scene restore="+UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingBoostFactor);
  FreshWorld();
  state.VanillaMode=true;SceneRuntime.Current.Brightness=.8f;SceneRuntime.ApplyCurrent();
  Check("X03 Scene camera edits never take over Lumen tone",Equal(UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingBoostFactor,1),"Archived Scene brightness=.8 is retained; effective boost remains "+UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().m_ToneMappingBoostFactor);
  FreshWorld();
  StyleEngine.CaptureBaseline();StyleEngine.ApplyLut("Other","");SceneRuntime.RestoreGame();
  Check("S05 restore game restores selected LUT",ColorCorrectionManager.instance.lastSelection==0,"original index=0 actual="+ColorCorrectionManager.instance.lastSelection);
  FreshWorld();
  var vals=new float[13];vals[10]=-.8f;
  var convert=typeof(LumenFX.Presets.PresetLibrary).GetMethod("TranslateLegacy",BindingFlags.Static|BindingFlags.NonPublic);
  var p1=(LumenFX.Presets.PresetDocument)convert.Invoke(null,new object[]{"test",vals,true});vals[10]=0;
  var p2=(LumenFX.Presets.PresetDocument)convert.Invoke(null,new object[]{"test",vals,true});
  Check("L04 importer distinguishes negative and neutral brightness",!Equal(p1.Brightness,p2.Brightness),"legacy -.8 maps to "+p1.Brightness+"; neutral maps to "+p2.Brightness);
  FreshWorld();
  state.SunStrength=3;LumenFX.IO.StateStore.SaveImmediate();state.SunStrength=1;LumenFX.IO.StateStore.Load();
  Check("L05 full UI sun-strength range survives reload",Equal(state.SunStrength,3),"UI permits 3; saved/reloaded="+state.SunStrength);
  FreshWorld();
  state.Warmth=.5f;TunerRuntime.ApplyAll();
  Call(new LumenFX.Core.TunerEngine(),"OnDestroy");
  UnityEngine.Object.Registry.Clear();DayNightProperties.instance=new DayNightProperties();new GameObject("Main Camera");new ColossalFramework.ToneMapping();
  var secondCityGradient=DayNightProperties.instance.m_LightColor;
  LumenFX.IO.StateStore.Load();TunerRuntime.ApplyAll();
  Check("L06 lighting rebuilt in second city without editing",!ReferenceEquals(secondCityGradient,DayNightProperties.instance.m_LightColor),"persisted warmth="+state.Warmth+" LightingDirty="+state.LightingDirty+" gradient reference unchanged="+ReferenceEquals(secondCityGradient,DayNightProperties.instance.m_LightColor));
  ConsolidationChecks();
  UiChecks();
  ExtraChecks();
  TransitionChecks();
  Console.WriteLine("SUMMARY PASS="+pass+" FAIL="+fail+". FAIL denotes a regression requirement that remains unmet.");
  Environment.ExitCode=fail==0?0:1;
 }

 static void TransitionChecks() {
  FreshWorld();
  DayNightProperties.instance.m_Exposure=.73f;
  TunerRuntime.CurrentState.SkyExposure=1.7f;
  LumenFX.Core.LightingMixer.Apply(TunerRuntime.CurrentState);
  TunerRuntime.CurrentState.SkyExposure=0f;
  LumenFX.Core.LightingMixer.Apply(TunerRuntime.CurrentState);
  Check("L12 exposure captures before writing and releases",Equal(DayNightProperties.instance.m_Exposure,.73f),"0 returns to the captured map exposure");
  DayNightProperties.instance.m_Exposure=.91f;
  LumenFX.Core.LightingMixer.Apply(TunerRuntime.CurrentState);
  Check("L13 released exposure is not written again",Equal(DayNightProperties.instance.m_Exposure,.91f),"another writer's later value is preserved");
  FreshWorld();
  var weather=WeatherManager.instance;weather.m_enableWeather=true;weather.m_properties.m_rainIsSnow=false;NetManager.instance.m_treatWetAsSnow=false;
  WorldController.WeatherEnabled=0;WorldController.RainIsSnow=1;WorldController.SnowyRoads=1;WorldController.Tick();
  WorldController.WeatherEnabled=-1;WorldController.RainIsSnow=-1;WorldController.SnowyRoads=-1;WorldController.Tick();
  Check("S12 Game releases individual weather switches",weather.m_enableWeather&&!weather.m_properties.m_rainIsSnow&&!NetManager.instance.m_treatWetAsSnow,"no full mode reset is necessary");
  weather.m_enableWeather=false;WorldController.WeatherEnabled=1;WorldController.Tick();WorldController.WeatherEnabled=-1;WorldController.Tick();
  Check("S13 weather recaptures on later acquisition",!weather.m_enableWeather,"new baseline is captured each time");
  FreshWorld();
  SimulationManager.instance.SimulationPaused=true;Time.unscaledDeltaTime=1f/60f;
  TimeController.CycleSpeedEnabled=true;TimeController.CycleWhilePaused=true;
  TimeController.Tick();TimeController.Tick();
  Check("S14 cycle starts in a freshly paused city",DayNightProperties.instance.m_TimeOfDay>12f,"public game day length and frame duration seed the rate");
  SimulationManager.instance.SimulationPaused=false;
  TimeController.SeparateDayNight=true;TimeController.CycleSpeed=2;TimeController.NightCycleSpeed=8;
  var speed=typeof(TimeController).GetMethod("SpeedFor",BindingFlags.NonPublic|BindingFlags.Static);
  Check("S15 night speed follows the visual clock",Equal((float)speed.Invoke(null,new object[]{22f/24f}),8f),"independent visual night while simulation still reports day");
  FreshWorld();
  DayNightProperties.instance.m_TimeOfDay=17f;WorldController.TimeOfDayHours=12f;
  var snapshot=new StyleData();StyleEngine.CaptureWorld(snapshot,true);
  Check("S16 explicit scene capture takes the visible hour",Equal(snapshot.TimeOfDay,17f),"automatic preferences and explicit snapshots have different intent");
  var state=TunerRuntime.CurrentState;float gamma=state.Gamma;
  bool accepted=LumenFX.LumenFXMod.ApplySuiteSection("<lumenfx><gamma>3</gamma><sunPower>bad</sunPower></lumenfx>");
  Check("L14 malformed numeric text rejects complete section",!accepted&&Equal(state.Gamma,gamma),"no partial success from an unparsed field");
  float density=AC.Density;
  accepted=AtmosphereFX.AtmosphereFXMod.ApplySuiteSection("<atmospherefx><density>0.001</density><noise>bad</noise></atmospherefx>");
  Check("A09 malformed numeric text rejects complete section",!accepted&&Equal(AC.Density,density),"no partial mutation");
  bool sunColor=CO.Instance.SunColor;
  accepted=ClassicLightFX.ClassicLightFXMod.ApplySuiteSection("<classiclightfx><sunColor>false</sunColor><sunStrength>bad</sunStrength></classiclightfx>");
  Check("C04 malformed Boolean rejects complete section",!accepted&&CO.Instance.SunColor==sunColor,"previous settings remain intact");
  gamma=SceneRuntime.Current.Gamma;
  accepted=SceneFX.SceneFXMod.ApplySuiteSection("<scenefx><gamma>3</gamma><brightness>bad</brightness></scenefx>");
  Check("S17 malformed text rejects complete scene section",!accepted&&Equal(SceneRuntime.Current.Gamma,gamma),"previous scene remains intact");
  FreshWorld();
  SceneRuntime.VanillaMode=true;SceneRuntime.SaveOptions();SceneRuntime.Flush();
  SceneRuntime.VanillaMode=false;SceneRuntime.LoadPersisted();
  Check("S18 Vanilla mode survives restart",SceneRuntime.VanillaMode,"options flush saves the selected mode");
  string options=Path.Combine(ConfigDir,"SceneFXOptions.xml");
  string blocker=options+".tmp";if(File.Exists(blocker))File.Delete(blocker);Directory.CreateDirectory(blocker);
  SceneRuntime.VanillaMode=false;SceneRuntime.SaveOptions();SceneRuntime.Flush();
  Directory.Delete(blocker);Time.realtimeSinceStartup+=2;SceneRuntime.CheckPendingSave();
  SceneRuntime.VanillaMode=true;SceneRuntime.LoadPersisted();
  Check("IO03 failed options save remains pending",!SceneRuntime.VanillaMode,"mode is retried after a failed write");
  FreshWorld();
  AtmosphereFX.Config.QuickPresets.ApplyOptimized();
  Check("A10 optimized label matches saved values",AtmosphereFX.Infrastructure.FxStorage.MatchesOptimized(AtmosphereFX.AtmosphereFXMod.ExportSuiteSection(),typeof(AtmosphereFX.AtmosphereFXMod)),"numeric comparison is independent of XML formatting");
  LumenFX.Presets.QuickPresets.ApplyOptimized();
  Check("L15 optimized label matches saved values",LumenFX.Infrastructure.FxStorage.MatchesOptimized(LumenFX.LumenFXMod.ExportSuiteSection(),typeof(LumenFX.LumenFXMod)),"absolute fields and tone included");
  ClassicLightFX.Core.QuickPresets.ApplyOptimized();
  Check("C05 optimized label matches saved values",ClassicLightFX.Infrastructure.FxStorage.MatchesOptimized(ClassicLightFX.ClassicLightFXMod.ExportSuiteSection(),typeof(ClassicLightFX.ClassicLightFXMod)),"DEFAULT has the classic features disabled");
  SceneFX.Core.QuickPresets.ApplyOptimized();
  Check("S19 optimized label matches saved values",SceneFX.Infrastructure.FxStorage.MatchesOptimized(SceneFX.SceneFXMod.ExportSuiteSection(),typeof(SceneFX.SceneFXMod)),"LUT name and world ownership included");
  accepted=SuiteManager.ApplySuiteProfile("<suiteProfile><lumenfx><gamma>bad</gamma></lumenfx><scenefx><brightness>0.1</brightness></scenefx></suiteProfile>");
  Check("X04 partial suite is reported as failure",!accepted,"some sections can apply; missing/rejected sections prevent success");
  Check("X05 API rejects unrelated XML roots",!LumenFX.LumenFXMod.ApplySuiteSection("<other/>")&&!AtmosphereFX.AtmosphereFXMod.ApplySuiteSection("<other/>")&&!ClassicLightFX.ClassicLightFXMod.ApplySuiteSection("<other/>")&&!SceneFX.SceneFXMod.ApplySuiteSection("<other/>"),"no accidental apply from an unrelated document");
  FreshWorld();
  TunerRuntime.CurrentState.VanillaMode=true;
  SceneRuntime.WorldChanged();
  Check("X06 weather-only action does not claim tone",!SceneFX.SceneFXMod.ActiveClaims.Contains("tone"),"claim actual writes instead of every possible feature");
  DayNightProperties.instance.m_Exposure=.72f;
  var look=new StyleData {Exposure=1.6f};StyleEngine.Apply(look);
  look.Exposure=0f;StyleEngine.Apply(look);
  Check("S20 Scene exposure zero releases its field",Equal(DayNightProperties.instance.m_Exposure,.72f),"same zero convention with and without Lumen");
  StyleEngine.RestoreGame();
  DayNightProperties.instance.m_Exposure=.85f;
  look.Exposure=1.5f;StyleEngine.Apply(look);StyleEngine.RestoreGame();
  Check("S21 Scene recaptures after release",Equal(DayNightProperties.instance.m_Exposure,.85f),"second acquisition does not restore the first baseline");
 }

 static void ExtraChecks() {

  FreshWorld();
  WorldController.ApplyTime(12f);
  Check("S06 game API uses hours",Equal(DayNightProperties.instance.m_TimeOfDay,12f)&&Equal(WorldController.ReadTimeHours(),12f),"no normalized-hour conversion");
  WorldController.TimeLocked=true;WorldController.ApplyTime(18f);WorldController.Tick();
  Check("S07 locked hour uses engine hours",Equal(DayNightProperties.instance.m_TimeOfDay,18f),"18 hours remains 18");
  FreshWorld();
  WorldController.ApplyTime(23f);
  Check("S22 night hour activates night flag and simulation frames",SimulationManager.instance.m_isNightTime&&Equal(SimulationManager.instance.m_currentDayTimeHour,23f)&&SimulationManager.instance.m_enableDayNight,"night simulation time and cycle enabled");
  FreshWorld();
  float oldDensity=AC.Density;
  bool accepted=AtmosphereFX.AtmosphereFXMod.ApplySuiteSection("<atmospherefx><density>0.001</density><noise>NaN</noise></atmospherefx>");
  Check("A05 rejected API section is atomic",!accepted&&Equal(AC.Density,oldDensity),"valid first field not committed before invalid second field");
  FreshWorld();
  var tone=UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>();
  float oldGamma=TunerRuntime.CurrentState.Gamma;
  accepted=LumenFX.LumenFXMod.ApplySuiteSection("<lumenfx><gamma>3</gamma><sunPower>Infinity</sunPower></lumenfx>");
  Check("L07 rejected API section is atomic",!accepted&&Equal(TunerRuntime.CurrentState.Gamma,oldGamma),"no partial state update");
  FreshWorld();
  string path=Path.Combine(ConfigDir,"LumenFX2.xml");
  File.WriteAllText(path,"<lumenFx><gamma>3</gamma><sunPower>NaN</sunPower></lumenFx>");
  oldGamma=TunerRuntime.CurrentState.Gamma;LumenFX.IO.StateStore.Load();
  Check("L08 malformed persisted state is atomic",Equal(TunerRuntime.CurrentState.Gamma,oldGamma),"failed XML load leaves old state intact");
  FreshWorld();
  accepted=AtmosphereFX.Config.QuickPresets.ApplyOptimized();
  Check("A06 canonical Default fog",accepted&&!AC.DynamicFog&&!AC.VolumeFog&&AC.CubemapFog&&Equal(AC.ScatterFalloff,59049f),"active Default flags and effective exponent");
  Check("A07 split fog depth applies",Equal(UnityEngine.Object.FindObjectOfType<FogEffect>().m_3DFogStart,3710f)&&Equal(UnityEngine.Object.FindObjectOfType<RenderProperties>().m_fogHeight,600f),"separate component depth fields");
  var export=AtmosphereFX.AtmosphereFXMod.ExportSuiteSection();
  AC.StaticStart=1;AtmosphereFX.AtmosphereFXMod.ApplySuiteSection(export);
  Check("A08 extended settings export round-trip",Equal(AC.StaticStart,3710f),"static depth is not omitted");
  FreshWorld();
  accepted=LumenFX.Presets.QuickPresets.ApplyOptimized();
  Check("L09 canonical Default lighting",accepted&&Equal(TunerRuntime.CurrentState.SunPower,5.5f)&&Equal(TunerRuntime.CurrentState.SkyExposure,1.102f)&&!TunerRuntime.CurrentState.AdaptiveExposure,"fixed exposure and absolute powers");
  var p=LumenFX.Presets.PresetLibrary.Capture("roundtrip");TunerRuntime.CurrentState.ResetToNeutral();LumenFX.Presets.PresetLibrary.Apply(p);
  Check("L10 preset stores every absolute light field",Equal(TunerRuntime.CurrentState.SunPower,5.5f)&&Equal(TunerRuntime.CurrentState.SkyMie,1.858f)&&Equal(TunerRuntime.CurrentState.SkyExposure,1.102f),"preset capture and apply");
  export=LumenFX.LumenFXMod.ExportSuiteSection();TunerRuntime.CurrentState.SkyExposure=2;LumenFX.LumenFXMod.ApplySuiteSection(export);
  Check("L11 extended export round-trip",Equal(TunerRuntime.CurrentState.SkyExposure,1.102f),"fixed exposure round-trip");
  FreshWorld();
  WorldController.SetChannel("rain",.8f);WorldController.TimeLocked=true;SceneRuntime.WorldChanged();
  accepted=SceneFX.Core.QuickPresets.ApplyOptimized();
  Check("S08 optimized releases temporary locks",accepted&&!WorldController.TimeLocked&&WorldController.RainIntensity<0f,"DEFAULT keeps the world game-owned");
  ColorCorrectionManager.instance.items = new[] { "Original", "Other" }; ColorCorrectionManager.instance.currentSelection = 0;
  accepted = SceneFX.Core.QuickPresets.ApplyOptimized();
  Check("S09 missing LUT is explicit",!accepted && StyleEngine.LastLutError.Contains("1539181199.Relight2Average")&&ColorCorrectionManager.instance.lastSelection==0,"no procedural or loosely matched replacement");
  FreshWorld();
  var lut=new ColossalFramework.ColorCorrectionLut();var bloom=new UnityStandardAssets.ImageEffects.Bloom();var rain=new RainParticleProperties();
  var style=new StyleData {LutEnabled=0,ToneEnabled=0,BloomEnabled=0,RainMotionBlur=1};
  CameraEffects.Apply(style);
  Check("S10 native camera toggles apply",!lut.enabled&&!bloom.enabled&&UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().enabled&&rain.ForceRainMotionBlur,"LUT, bloom and rain blur; tone is left to Lumen");
  CameraEffects.Restore();
  Check("S11 native camera toggles restore",lut.enabled&&bloom.enabled&&UnityEngine.Object.FindObjectOfType<ColossalFramework.ToneMapping>().enabled&&!rain.ForceRainMotionBlur,"all captured flags restored");
  FreshWorld();
  string atomic=Path.Combine(ConfigDir,"atomic.xml");AtmosphereFX.Infrastructure.FxStorage.WriteText(atomic,"old");AtmosphereFX.Infrastructure.FxStorage.WriteText(atomic,"new");
  Check("IO01 atomic write retains previous file",File.ReadAllText(atomic)=="new"&&File.ReadAllText(atomic+".bak")=="old","last good version is recoverable");
  FreshWorld();
  string blocker=Path.Combine(ConfigDir,"LumenFX2.xml.tmp");if(File.Exists(blocker))File.Delete(blocker);Directory.CreateDirectory(blocker);
  TunerRuntime.CurrentState.Brightness=.6f;LumenFX.IO.StateStore.SaveImmediate();
  bool dirty=(bool)typeof(LumenFX.IO.StateStore).GetField("_dirty",BindingFlags.Static|BindingFlags.NonPublic).GetValue(null);
  Directory.Delete(blocker);Time.realtimeSinceStartup+=2;LumenFX.IO.StateStore.CheckPendingSave();
  Check("IO02 failed save remains pending and retries",dirty&&File.ReadAllText(path).Contains("<brightness>0.6</brightness>"),"failed write followed by automatic recovery");
 }
}
